import { useState, type FormEvent, type ReactNode } from 'react';
import type { ApiContractor, ApiTicket, ApiTicketSuggestion, TicketPriority } from '../api/maintenance';
import type { Property } from '../data/mockData';

interface Props {
  tickets: ApiTicket[]; suggestions: ApiTicketSuggestion[]; properties: Property[]; contractors: ApiContractor[];
  loading: boolean; error: string | null; onRetry: () => void;
  onCreate: (input: { property_id: string; title: string; description: string; priority: TicketPriority }) => Promise<void>;
  onConfirm: (suggestion: ApiTicketSuggestion) => Promise<void>; onReject: (id: string) => Promise<void>;
  onCreateContractor: (input: { name: string; phone?: string; specialty?: string; notes?: string }) => Promise<void>;
  onUpdateContractor: (id: string, input: { name: string; phone?: string; specialty?: string; notes?: string }) => Promise<void>;
  onDeactivateContractor: (id: string) => Promise<void>; onAssignContractor: (ticketId: string, contractorId: string) => Promise<void>;
}

export function TicketsPage({ tickets, suggestions, properties, contractors, loading, error, onRetry, onCreate, onConfirm, onReject, onCreateContractor, onUpdateContractor, onDeactivateContractor, onAssignContractor }: Props) {
  const [ticketFormOpen, setTicketFormOpen] = useState(false); const [contractorFormOpen, setContractorFormOpen] = useState(false); const [editingContractor, setEditingContractor] = useState<ApiContractor | null>(null);
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [propertyId, setPropertyId] = useState(''); const [priority, setPriority] = useState<TicketPriority>('medium');
  const [contractorName, setContractorName] = useState(''); const [contractorPhone, setContractorPhone] = useState(''); const [contractorSpecialty, setContractorSpecialty] = useState(''); const [contractorNotes, setContractorNotes] = useState('');
  const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState<string | null>(null); const [selectedContractorByTicket, setSelectedContractorByTicket] = useState<Record<string, string>>({});
  const activeContractors = contractors.filter((contractor) => contractor.is_active);
  const propertyName = (id: string) => properties.find((property) => property.id === id)?.name ?? 'Property unavailable';
  const closeTicketForm = () => { setTicketFormOpen(false); setTitle(''); setDescription(''); setPropertyId(''); };
  const submitTicket = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setActionError(null); try { await onCreate({ property_id: propertyId, title, description, priority }); closeTicketForm(); } catch (err: any) { setActionError(err.message || 'Unable to create the ticket. Try again.'); } finally { setSaving(false); } };
  const submitContractor = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setActionError(null); try { const input = { name: contractorName, phone: contractorPhone || undefined, specialty: contractorSpecialty || undefined, notes: contractorNotes || undefined }; if (editingContractor) { await onUpdateContractor(editingContractor.id, input); } else { await onCreateContractor(input); } setContractorName(''); setContractorPhone(''); setContractorSpecialty(''); setContractorNotes(''); setEditingContractor(null); setContractorFormOpen(false); } catch (err: any) { setActionError(err.message || 'Unable to save the contractor. Try again.'); } finally { setSaving(false); } };
  const editContractor = (contractor: ApiContractor) => { setEditingContractor(contractor); setContractorName(contractor.name); setContractorPhone(contractor.phone || ''); setContractorSpecialty(contractor.specialty || ''); setContractorNotes(contractor.notes || ''); setContractorFormOpen(true); };
  const assign = async (ticketId: string) => { const contractorId = selectedContractorByTicket[ticketId]; if (!contractorId) { setActionError('Select an active contractor before assigning this ticket.'); return; } setSaving(true); setActionError(null); try { await onAssignContractor(ticketId, contractorId); } catch (err: any) { setActionError(err.message || 'Unable to assign this contractor. Try again.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
    <header className="flex flex-col gap-4 border-b border-[#EBE6DD] pb-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#0F3D5E]">Maintenance · {tickets.length} tickets</p><h1 className="mt-1 text-2xl font-bold text-[#1C1B18]">Property Maintenance</h1><p className="text-sm text-[#78716C]">Track issues and record the contractor contact handling each ticket.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setEditingContractor(null); setContractorName(''); setContractorPhone(''); setContractorSpecialty(''); setContractorNotes(''); setContractorFormOpen(true); }} className="rounded-xl border border-[#0F3D5E] px-4 py-2.5 text-xs font-bold text-[#0F3D5E]">Add contractor</button><button type="button" onClick={() => setTicketFormOpen(true)} className="rounded-xl bg-[#0F3D5E] px-4 py-2.5 text-xs font-bold text-white">Create ticket</button></div></header>
    {(error || actionError) && <section role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error || actionError} {error && <button type="button" className="font-bold underline" onClick={onRetry}>Try again</button>}</section>}
    {loading && <p className="rounded-xl border border-[#EBE6DD] bg-white p-5 text-sm text-[#78716C]">Loading maintenance work...</p>}
    {!loading && !error && <section className="rounded-2xl border border-[#EBE6DD] bg-white p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-[#1C1B18]">Contractor contacts</h2><p className="text-sm text-[#78716C]">Contacts only — contractors do not sign in to Vayca.</p></div><span className="rounded-full bg-[#F0F6FA] px-2 py-1 text-xs font-bold text-[#0F3D5E]">{activeContractors.length} active</span></div>{contractors.length === 0 ? <p className="mt-4 text-sm text-[#78716C]">No contractor contacts yet. Add one before assigning work.</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{contractors.map((contractor) => <article key={contractor.id} className="rounded-xl border border-[#EBE6DD] bg-[#FAF8F5] p-3"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold text-[#1C1B18]">{contractor.name}</h3><p className="text-xs text-[#78716C]">{contractor.specialty || 'No specialty recorded'}</p></div><span className="text-xs font-semibold text-[#78716C]">{contractor.is_active ? 'Active' : 'Inactive'}</span></div>{contractor.phone && <p className="mt-2 text-sm text-[#3B3735]">{contractor.phone}</p>}<div className="mt-3 flex gap-3"><button type="button" disabled={saving} onClick={() => editContractor(contractor)} className="text-xs font-bold text-[#0F3D5E] underline">Edit contact</button>{contractor.is_active && <button type="button" disabled={saving} onClick={() => void onDeactivateContractor(contractor.id)} className="text-xs font-bold text-[#C25730] underline">Deactivate contact</button>}</div></article>)}</div>}</section>}
    {!loading && !error && suggestions.length > 0 && <section className="space-y-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-bold text-[#1C1B18]">Chatbot suggestions need staff confirmation</h2>{suggestions.map((suggestion) => <article key={suggestion.id} className="rounded-xl border border-amber-200 bg-white p-4"><p className="font-bold">{suggestion.title}</p><p className="mt-1 text-sm text-[#3B3735]">{suggestion.description}</p><p className="mt-2 text-xs text-[#78716C]">{propertyName(suggestion.property_id)} · {suggestion.priority}</p><div className="mt-3 flex gap-2"><button type="button" className="rounded-lg bg-[#0F3D5E] px-3 py-2 text-xs font-bold text-white" onClick={() => void onConfirm(suggestion)}>Confirm ticket</button><button type="button" className="rounded-lg border border-[#EBE6DD] px-3 py-2 text-xs font-bold" onClick={() => void onReject(suggestion.id)}>Reject</button></div></article>)}</section>}
    {!loading && !error && tickets.length === 0 && suggestions.length === 0 && <p className="rounded-xl border border-[#EBE6DD] bg-white p-8 text-center text-sm text-[#78716C]">No maintenance tickets yet. Create one when a property issue is reported.</p>}
    {!loading && !error && tickets.length > 0 && <section className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{tickets.map((ticket) => <article key={ticket.id} className="rounded-xl border border-[#EBE6DD] bg-white p-4"><div className="flex justify-between gap-2"><h2 className="font-bold text-[#1C1B18]">{ticket.title}</h2><span className="rounded-full bg-[#FDF4F0] px-2 py-0.5 text-xs font-bold text-[#C25730]">{ticket.priority}</span></div><p className="mt-2 text-sm text-[#3B3735]">{ticket.description}</p><p className="mt-3 text-xs text-[#78716C]">{propertyName(ticket.property_id)} · {ticket.status.replace('_', ' ')}</p>{!['resolved', 'cancelled'].includes(ticket.status) && <div className="mt-4 border-t border-[#EBE6DD] pt-3"><label className="block text-xs font-bold text-[#3B3735]">Assign contractor<select aria-label={`Contractor for ${ticket.title}`} value={selectedContractorByTicket[ticket.id] || ''} onChange={(event) => setSelectedContractorByTicket((current) => ({ ...current, [ticket.id]: event.target.value }))} className="mt-1 w-full rounded-lg border border-[#DDD7CC] bg-white p-2 text-sm"><option value="">Select active contractor</option>{activeContractors.map((contractor) => <option key={contractor.id} value={contractor.id}>{contractor.name}{contractor.specialty ? ` — ${contractor.specialty}` : ''}</option>)}</select></label><button type="button" disabled={saving || activeContractors.length === 0} onClick={() => void assign(ticket.id)} className="mt-2 w-full rounded-lg bg-[#0F3D5E] p-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">Assign contractor</button></div>}</article>)}</section>}
    {ticketFormOpen && <Modal title="Create maintenance ticket"><form onSubmit={(event) => void submitTicket(event)} className="space-y-3"><label className="block text-sm font-semibold">Property<select required value={propertyId} onChange={(event) => setPropertyId(event.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Select property</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name}</option>)}</select></label><label className="block text-sm font-semibold">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Description<textarea required value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Priority<select value={priority} onChange={(event) => setPriority(event.target.value as TicketPriority)} className="mt-1 w-full rounded-lg border p-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><ModalActions onCancel={closeTicketForm} saving={saving} label="Create ticket" /></form></Modal>}
    {contractorFormOpen && <Modal title={editingContractor ? 'Edit contractor contact' : 'Add contractor contact'}><form onSubmit={(event) => void submitContractor(event)} className="space-y-3"><label className="block text-sm font-semibold">Name<input required value={contractorName} onChange={(event) => setContractorName(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Phone<input value={contractorPhone} onChange={(event) => setContractorPhone(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Specialty<input value={contractorSpecialty} onChange={(event) => setContractorSpecialty(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Notes<textarea value={contractorNotes} onChange={(event) => setContractorNotes(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><ModalActions onCancel={() => { setEditingContractor(null); setContractorFormOpen(false); }} saving={saving} label="Save contact" /></form></Modal>}
  </div>;
}

function Modal({ title, children }: { title: string; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1C1B18]/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></div></div>; }
function ModalActions({ onCancel, saving, label }: { onCancel: () => void; saving: boolean; label: string }) { return <div className="flex gap-2"><button type="button" onClick={onCancel} className="flex-1 rounded-lg border p-2">Cancel</button><button disabled={saving} className="flex-1 rounded-lg bg-[#0F3D5E] p-2 font-bold text-white">{saving ? 'Saving...' : label}</button></div>; }
