import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { TicketsPage } from './TicketsPage';

const property = { id: 'property-1', name: 'Villa Yasmine' } as any;
const suggestion = { id: 'suggestion-1', property_id: 'property-1', booking_id: null, conversation_id: null, title: 'Leaking sink', description: 'Guest reports a leak.', category: 'plumbing', priority: 'high', status: 'pending', created_at: '2026-08-18T10:00:00Z' } as const;

describe('TicketsPage', () => {
  const props = { tickets: [], suggestions: [], properties: [property], contractors: [], loading: false, error: null, onRetry: vi.fn(), onCreate: vi.fn().mockResolvedValue(undefined), onConfirm: vi.fn().mockResolvedValue(undefined), onReject: vi.fn().mockResolvedValue(undefined), onCreateContractor: vi.fn().mockResolvedValue(undefined), onUpdateContractor: vi.fn().mockResolvedValue(undefined), onDeactivateContractor: vi.fn().mockResolvedValue(undefined), onAssignContractor: vi.fn().mockResolvedValue(undefined), filters: {}, onFiltersChange: vi.fn(), statusHistories: {}, onLoadStatusHistory: vi.fn().mockResolvedValue(undefined), onUpdateStatus: vi.fn().mockResolvedValue(undefined) };
  it('shows empty and retryable failure states', () => { const { rerender } = render(<TicketsPage {...props} />); expect(screen.getByText(/No maintenance tickets match/)).toBeInTheDocument(); rerender(<TicketsPage {...props} error="Unable to reach the API." />); fireEvent.click(screen.getByRole('button', { name: 'Try again' })); expect(props.onRetry).toHaveBeenCalled(); });
  it('creates a ticket using the selected property', () => { render(<TicketsPage {...props} />); fireEvent.click(screen.getByRole('button', { name: 'Create ticket' })); fireEvent.change(screen.getAllByLabelText('Property')[1], { target: { value: 'property-1' } }); fireEvent.change(screen.getByLabelText('Title'), { target: { value: 'Broken AC' } }); fireEvent.change(screen.getByLabelText('Description'), { target: { value: 'AC is not cooling.' } }); fireEvent.click(screen.getAllByRole('button', { name: 'Create ticket' })[1]); expect(props.onCreate).toHaveBeenCalledWith(expect.objectContaining({ property_id: 'property-1', title: 'Broken AC' })); });
  it('lets staff confirm or reject a suggestion', () => { render(<TicketsPage {...props} suggestions={[suggestion]} />); fireEvent.click(screen.getByRole('button', { name: 'Confirm ticket' })); expect(props.onConfirm).toHaveBeenCalledWith(suggestion); fireEvent.click(screen.getByRole('button', { name: 'Reject' })); expect(props.onReject).toHaveBeenCalledWith('suggestion-1'); });
  it('creates a contractor contact and assigns an active contractor', async () => { const ticket = { id: 'ticket-1', property_id: 'property-1', title: 'Broken AC', description: 'Not cooling.', priority: 'high', status: 'open' } as any; const contractor = { id: 'contractor-1', name: 'Amine', phone: null, specialty: 'HVAC', notes: null, is_active: true } as any; render(<TicketsPage {...props} tickets={[ticket]} contractors={[contractor]} />); fireEvent.change(screen.getByLabelText('Contractor for Broken AC'), { target: { value: 'contractor-1' } }); fireEvent.click(screen.getByRole('button', { name: 'Assign contractor' })); await waitFor(() => expect(props.onAssignContractor).toHaveBeenCalledWith('ticket-1', 'contractor-1')); await waitFor(() => expect(screen.getByRole('button', { name: 'Assign contractor' })).not.toBeDisabled()); fireEvent.click(screen.getByRole('button', { name: 'Add contractor' })); fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Noura' } }); fireEvent.click(screen.getByRole('button', { name: 'Save contact' })); await waitFor(() => expect(props.onCreateContractor).toHaveBeenCalledWith(expect.objectContaining({ name: 'Noura' }))); });
  it('sends filters to the parent and shows status history', async () => { const ticket = { id: 'ticket-1', property_id: 'property-1', title: 'Broken AC', description: 'Not cooling.', priority: 'high', status: 'assigned' } as any; render(<TicketsPage {...props} tickets={[ticket]} statusHistories={{ 'ticket-1': [{ id: 'history-1', ticket_id: 'ticket-1', from_status: 'open', to_status: 'assigned', changed_by_user_id: 'user-1', changed_at: '2026-08-24T10:00:00Z', note: 'Assigned.' }] as any }} />); fireEvent.change(screen.getByLabelText('Filter by status'), { target: { value: 'assigned' } }); expect(props.onFiltersChange).toHaveBeenCalledWith({ status: 'assigned' }); fireEvent.click(screen.getByRole('button', { name: 'Show status history' })); await waitFor(() => expect(props.onLoadStatusHistory).toHaveBeenCalledWith('ticket-1')); expect(screen.getByText(/open → assigned/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Start work' })); await waitFor(() => expect(props.onUpdateStatus).toHaveBeenCalledWith('ticket-1', 'in_progress', undefined)); });
});
