import { useState } from 'react';
import type { Property } from '../data/mockData';
import type { ApiTicket, ApiTicketSuggestion, TicketPriority } from '../api/maintenance';

interface Props {
  tickets: ApiTicket[]; suggestions: ApiTicketSuggestion[]; properties: Property[];
  loading: boolean; error: string | null; onRetry: () => void;
  onCreate: (input: { property_id: string; title: string; description: string; priority: TicketPriority }) => Promise<void>;
  onConfirm: (suggestion: ApiTicketSuggestion) => Promise<void>; onReject: (id: string) => Promise<void>;
}

export function TicketsPage({ tickets, suggestions, properties, loading, error, onRetry, onCreate, onConfirm, onReject }: Props) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [propertyId, setPropertyId] = useState(''); const [priority, setPriority] = useState<TicketPriority>('medium'); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await onCreate({ property_id: propertyId, title, description, priority }); setOpen(false); setTitle(''); setDescription(''); } finally { setSaving(false); } };
  const propertyName = (id: string) => properties.find((property) => property.id === id)?.name ?? 'Property unavailable';
  return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
    <header className="flex flex-col gap-4 border-b border-[#EBE6DD] pb-6 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#0F3D5E]">Maintenance · {tickets.length} tickets</p><h1 className="mt-1 text-2xl font-bold text-[#1C1B18]">Property Maintenance</h1><p className="text-sm text-[#78716C]">Create and review property issues. Contractor assignment and status transitions follow later workflow steps.</p></div><button type="button" onClick={() => setOpen(true)} className="rounded-xl bg-[#0F3D5E] px-4 py-2.5 text-xs font-bold text-white">Create ticket</button></header>
    {error && <section className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error} <button type="button" className="font-bold underline" onClick={onRetry}>Try again</button></section>}
    {loading && <p className="rounded-xl border border-[#EBE6DD] bg-white p-5 text-sm text-[#78716C]">Loading maintenance work...</p>}
    {!loading && !error && suggestions.length > 0 && <section className="space-y-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-bold text-[#1C1B18]">Chatbot suggestions need staff confirmation</h2>{suggestions.map((suggestion) => <article key={suggestion.id} className="rounded-xl border border-amber-200 bg-white p-4"><p className="font-bold">{suggestion.title}</p><p className="mt-1 text-sm text-[#3B3735]">{suggestion.description}</p><p className="mt-2 text-xs text-[#78716C]">{propertyName(suggestion.property_id)} · {suggestion.priority}</p><div className="mt-3 flex gap-2"><button type="button" className="rounded-lg bg-[#0F3D5E] px-3 py-2 text-xs font-bold text-white" onClick={() => void onConfirm(suggestion)}>Confirm ticket</button><button type="button" className="rounded-lg border border-[#EBE6DD] px-3 py-2 text-xs font-bold" onClick={() => void onReject(suggestion.id)}>Reject</button></div></article>)}</section>}
    {!loading && !error && tickets.length === 0 && suggestions.length === 0 && <p className="rounded-xl border border-[#EBE6DD] bg-white p-8 text-center text-sm text-[#78716C]">No maintenance tickets yet. Create one when a property issue is reported.</p>}
    {!loading && !error && tickets.length > 0 && <section className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{tickets.map((ticket) => <article key={ticket.id} className="rounded-xl border border-[#EBE6DD] bg-white p-4"><div className="flex justify-between gap-2"><h2 className="font-bold text-[#1C1B18]">{ticket.title}</h2><span className="rounded-full bg-[#FDF4F0] px-2 py-0.5 text-xs font-bold text-[#C25730]">{ticket.priority}</span></div><p className="mt-2 text-sm text-[#3B3735]">{ticket.description}</p><p className="mt-3 text-xs text-[#78716C]">{propertyName(ticket.property_id)} · {ticket.status.replace('_', ' ')}</p></article>)}</section>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1C1B18]/50 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-md space-y-3 rounded-2xl bg-white p-6"><h2 className="text-lg font-bold">Create maintenance ticket</h2><label className="block text-sm font-semibold">Property<select required value={propertyId} onChange={(event) => setPropertyId(event.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Select property</option>{properties.map((property) => <option key={property.id} value={property.id}>{property.name}</option>)}</select></label><label className="block text-sm font-semibold">Title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Description<textarea required value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-semibold">Priority<select value={priority} onChange={(event) => setPriority(event.target.value as TicketPriority)} className="mt-1 w-full rounded-lg border p-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><div className="flex gap-2"><button type="button" onClick={() => setOpen(false)} className="flex-1 rounded-lg border p-2">Cancel</button><button disabled={saving} className="flex-1 rounded-lg bg-[#0F3D5E] p-2 font-bold text-white">{saving ? 'Creating...' : 'Create ticket'}</button></div></form></div>}
  </div>;
}
